name: books_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  visibility_aware_state: ^1.0.5
  get_it: ^7.6.7
  dio: ^5.4.0
  uuid: ^4.3.3
  dio_smart_retry: ^6.0.0
  dio_http2_adapter: ^2.4.0
  connectivity_plus: ^5.0.2
  intl: ^0.18.1
  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

